# Generated by Django 4.1.5 on 2026-02-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_useractiverecipe_unique_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershoppinglist',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='usershoppinglist',
            name='quantity_str',
        ),
        migrations.RemoveField(
            model_name='usershoppinglist',
            name='quantity_unit',
        ),
    ]
